### ISSUE TITLE
ring-anti-forgery and web services

### ISSUE THREAD

**Issue by mynomoto** [ring-clojure/ring-anti-forgery#2]
On the readme there is a caveat about using ring-anti-forgery with web services. But it can work with those just fine and would even work out of the box if the default access-denied response included the token on the header - if the client just send the token back with its request.

Could this header be in the access-denied response by default? Or can you think about reasons not to do it?

Thanks.

**Comment by Parth-Brahmbhatt** [comment]
I still don't get this. In apache storm we have same post route being used by our web page and the rest api. In order to use CSRF protection I will now have to create duplicate routes?

**Comment by weavejester** [comment]
CSRF attacks come about because form POSTs can be triggered across domains. If the same URI is intended to receive authenticated POST requests from both a browser and an API client, then you need some way of determining whether or not the request comes from the browser or API client.

For example, perhaps you use cookie-based sessions to authenticate browsers, and HTTP Basic Auth to authenticate API clients. You could have some custom middleware that checks to see how the user is authenticating; if it's via a session, then the anti-forgery middleware is added, otherwise it leaves it out.
