### ISSUE TITLE
Anti forgery token fails and it keeps failing even with a refresh

### ISSUE THREAD

**Issue by ekaitz-zarraga** [ring-clojure/ring-anti-forgery#23]
I'm getting some trouble with the standard configuration of the library.
It gets to a point where it starts returning `Invalid Anti-Forgery token` errors and it's impossible to correct it.

I've had this problem with this exact project I'm coding:
https://gitlab.com/ekaitz-zarraga/asktodon/tree/master

The handler is very simple, it's just a couple of routes. When the form is sent it the anti-forgery check fails randomly and once it started failing it continues failing ad-infinitum.

The failing behaviour can be forced by changing the csrf-field on the browser once by hand, after that it will constantly fail even if the form window is refreshed and new tokens are issued.

Is this a misconfiguration or is it an error from here?
I don't really understand what's going on with this.

**Comment by ekaitz-zarraga** [comment]
It's consistent, it happens in every execution but it starts correctly and then it breaks at some point I can't predict.

I've checked the requests and all of them have a fresh new token but I don't know why it isn't the valid one.

The easiest way to replicate it is to edit the form in the browser and change it's value to force the token to fail. Once it failed, all the next requests will fail even if the client was refreshed and the token sent is different.

All the test code can be found here:
https://gitlab.com/ekaitz-zarraga/asktodon/blob/master/src/asktodon/handler.clj

But with there's not really nothing else than:
``` clojure
(def app
   (routes
     (wrap-defaults app-routes site-defaults)
     (route/resources "/")
     (route/not-found "Not Found")))
```

And a route with the csrf token inserted from the request:
``` clojure

  (GET "/identify"
       []
       (fn [req]
         (ok-html (vws/identification-form (:anti-forgery-token req)))))
```

And this should work out of the box, right?

**Comment by weavejester** [comment]
I've looked through your code, and you're doing a few things wrong that cumulatively result in the strange behavior you're seeing.

The first thing to understand is that Compojure resolves routes in order until it finds one that matches the request. A matching route is one that returns a response map; a route that doesn't match returns `nil`.

Because some of your routes return `nil` as a result of `when` conditions and side-effects like `spit`, these routes will be considered as not matching under certain conditions. You probably don't want this.

You'll also find that when the browser looks for `/favicon.ico`, it's hitting your `GET /:campaign` route, since that's the first route that matches.

The second thing you need to understand is how sessions work in Ring. There is a `:session` key on the request map that contains the current session, and you can update this and add the altered session map to the response under the `:session` key to persist it.

However, in your `GET /:campaign` route, you're overwriting the session completely, ignoring the data that's there already. The anti-forgery middleware uses the session to persist the anti-forgery token, so you're unintentionally overwriting this.

If you fix your session handling and routing, you should find that your application will work.

**Comment by ekaitz-zarraga** [comment]
Thank you for your time checking the code. I **really** appreciate your help.

I made some changes on the code taking in account what you said. I attached the previous session to the responses and added the extra field on it and now it works. I misunderstood the examples in the session section of ring...

I also removed the nil-ending routes but I think they had no relation with this specific issue.

I have to test it more deeply but it looks pretty nice. I can't make it fail forever like I did in the past. It's like as I was clearing the session it was breaking the CSRF token too and it was unable to check it.

Thank you very much for the help. It was my fault 100%. Now I understand better.

I'll close this issue.
